### PR TITLE
`Ember.Select` `.create`, `.reopen`, `.extend` do not issue deprecation warnings

### LINKED ISSUE #3: Add a test asserting `Ember.Select.create` works

### PR DESCRIPTION
**Pull request by bantic**
(also fixes type "doest" in some tests)

related PR in ember: https://github.com/emberjs/ember.js/pull/11416

fixes #3

### CODE REVIEW

**Comment by rwjblue** [comment]
Might also want to add one for `.extend`?

**Comment by bantic** [comment]
@rwjblue good idea. done! We do not actually issue any deprecations in Ember for `extend` or `reopen` of `Ember.Select`, [only creation](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/select.js#L679-L682). If that seems like an oversight let me know. 

Seems worthwhile to cover `extend` and `reopen` in this addon regardless.

**Comment by rwjblue** [comment]
Yes, we should deprecate `.extend` also.  It is **very** common to put something like:

``` javascript
// app/components/my-special-select.js

export default Ember.Select.extend({
  // special things here
});
```

**Comment by bantic** [comment]
@rwjblue The thinking was that as long as we are issuing the deprecation from `init`, cases where someone extended `Ember.Select` would still eventually hit that deprecation when the extended class was instantiated later.

Adding a deprecation to `extend` as well would probably end up with at least 2 deprecation warnings. Putting it only on `init` seemed like the best way to achieve the goal (discourage `Ember.Select` use) with minimal noise.

I am happy to add the warnings to `extend` etc, though, if you think it's ok to have those multiple warnings.

**Comment by rwjblue** [comment]
Thank you for thinking it through and explaining.  I agree with you completely, no need for two deprecations.

**Pull request merged**
