### PR TITLE
Moving ember-view blueprint into addon

### PR DESCRIPTION
**Pull request by jasonmit**
See: https://github.com/ember-cli/ember-cli/pull/5607

### CODE REVIEW

**Comment by jasonmit** [comment]
Tests failing for other reasons

**Comment by rwjblue** [comment]
Needs to bring the view-test blueprint also.

**Comment by jasonmit** [comment]
@rwjblue all fixed

**Comment by rwjblue** [comment]
Failures are issues with master (not this PR).

**Pull request merged**
